pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                    label 'docker'  // Make sure Jenkins is running on a node labeled 'docker' or adjust accordingly
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                    label 'docker'  // Again, ensure that Jenkins has access to this node
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
